#!/usr/bin/env python3
"""
categorize_pubpeer_comments.py — tag each PubPeer comment by its NATURE,
never by a verdict on the paper.

Reads data/flags/pubpeer_flags.json (written by
sensors/pubpeer_comment_checker.py) and classifies every stored comment body
into one category using deterministic, auditable rules -- no model calls,
same "signal not verdict" discipline as every other sensor in this project
(plan.md §0). A comment alleging image duplication is an unverified CLAIM
about the figure until a human checks it; this script categorizes the claim,
it does not adjudicate it.

Categories (checked in this priority order -- a comment citing an official
retraction notice AND containing an image is still, first and foremost, an
official_editorial_action):

  official_editorial_action     comment reports/links a real Expression of
                                 Concern, retraction notice, or other formal
                                 journal/publisher action. Qualitatively
                                 different from opinion -- it's reporting a
                                 fact that already happened, independently
                                 verifiable via the linked notice.
  external_investigation_reference  comment cites a published research-
                                 integrity investigation or a known cluster
                                 pattern (e.g. an ethics-committee protocol
                                 shared across many papers) -- third-party
                                 scrutiny, not the commenter's own claim.
  author_response                the paper's author (or someone claiming to
                                 be) replying -- rebuttal/context, not itself
                                 an accusation. Backed by the sensor's own
                                 structural is_from_author flag, not text
                                 matching.
  conflict_of_interest           editor/reviewer <-> author relationship
                                 concerns.
  reference_integrity            citations/bibliography questioned as
                                 unreliable, missing, or fabricated.
  image_integrity                image attached to the comment (structural
                                 signal: PubPeer comments almost always
                                 attach a figure crop when alleging
                                 duplication/manipulation) or textual
                                 duplication language.
  methodology_question           procedural/methods clarification requests
                                 with no other signal above.
  uncategorized                  no rule matched -- left for human/agent
                                 read rather than a forced guess. Expect a
                                 meaningful uncategorized fraction; that's
                                 the design working, not a gap to paper over.

Output: data/flags/pubpeer_comment_categories.json -- one record per comment,
each carrying paper_doi, pubpeer_url, comment index, category, the matched
rule (for auditability), and the original text/evidence untouched. Does NOT
modify pubpeer_flags.json (that file is regenerated by the sensor on every
re-run and must stay the sensor's own untouched output).

Usage:
  python graph_processing/categorize_pubpeer_comments.py
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FLAGS_JSON = REPO_ROOT / "data" / "flags" / "pubpeer_flags.json"
OUTPUT_JSON = REPO_ROOT / "data" / "flags" / "pubpeer_comment_categories.json"

# Order matters: first matching rule wins.
RULES: list[tuple[str, str, re.Pattern]] = [
    (
        "official_editorial_action", "eoc_or_retraction_language",
        re.compile(r"expression of concern|has been retracted|retraction notice|editor'?s note", re.I),
    ),
    (
        "external_investigation_reference", "third_party_investigation_language",
        re.compile(
            r"research integrity|identified as one of a series|protocol n[°o]|ethics committee|"
            r"peer review\)|highlighted by researchers",
            re.I,
        ),
    ),
    # author_response is handled structurally (is_from_author), not by regex -- see categorize().
    (
        "conflict_of_interest", "editor_author_conflict_language",
        re.compile(r"conflict", re.I),  # combined with editor/reviewer check in categorize()
    ),
    (
        "reference_integrity", "questioned_references_language",
        re.compile(r"\b(reference|citation|bibliograph)\w*\b.{0,40}\b(unreliab|question|missing|does not support|fabricat)", re.I),
    ),
    (
        "image_integrity", "duplication_reuse_language",
        re.compile(r"identical|duplicat|same source|rotated|overlap|reused|re-use", re.I),
    ),
    (
        "methodology_question", "methods_clarification_language",
        re.compile(r"\b(method|protocol|characteriz|assess|clarify|explain|could you)\b", re.I),
    ),
]


def categorize(comment: dict) -> tuple[str, str]:
    """Returns (category, matched_rule)."""
    text = comment.get("text") or ""

    if comment.get("author_response"):
        return "author_response", "structural_is_from_author_flag"

    for category, rule_name, pattern in RULES:
        if category == "conflict_of_interest":
            if pattern.search(text) and re.search(r"editor|reviewer", text, re.I):
                return category, rule_name
            continue
        if pattern.search(text):
            return category, rule_name

    if comment.get("images"):
        return "image_integrity", "structural_image_attachment"

    return "uncategorized", "no_rule_matched"


def main() -> None:
    if not FLAGS_JSON.exists():
        print(f"ERROR: {FLAGS_JSON} not found -- run sensors/pubpeer_comment_checker.py first.")
        sys.exit(1)

    records = json.loads(FLAGS_JSON.read_text())
    with_comments = [r for r in records if r.get("comments")]

    categorized = []
    counts: dict[str, int] = {}
    for r in with_comments:
        for c in r["comments"]:
            category, rule = categorize(c)
            counts[category] = counts.get(category, 0) + 1
            categorized.append({
                "paper_doi": r["paper_doi"],
                "paper_title": r.get("paper_title"),
                "pubpeer_url": r.get("pubpeer_url"),
                "comment_n": c.get("n"),
                "by": c.get("by"),
                "author_response": c.get("author_response"),
                "accepted_at": c.get("accepted_at"),
                "category": category,
                "matched_rule": rule,
                "text": c.get("text"),
                "images": c.get("images"),
            })

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(categorized, indent=2, ensure_ascii=False))

    print(f"  categorized {len(categorized)} comments across {len(with_comments)} papers")
    print(f"  report written -> {OUTPUT_JSON.relative_to(REPO_ROOT)}\n")

    # No comments at all is a legitimate state (PubPeer returned nothing, or the
    # sensor hasn't been re-run against a fresh candidate set) -- report it and
    # stop, rather than dividing by a zero total below.
    if not categorized:
        print("  no PubPeer comments to categorize -- nothing to summarize.")
        return

    print("  category breakdown:")
    for cat, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        pct = 100 * n / len(categorized)
        print(f"    {cat:<32}: {n:>4}  ({pct:.1f}%)")

    uncategorized_pct = 100 * counts.get("uncategorized", 0) / len(categorized)
    print(
        f"\n  NOTE: categories describe the comment's NATURE, not the paper's "
        f"guilt -- an image_integrity comment is an unverified claim until a "
        f"human checks the figure. {uncategorized_pct:.1f}% uncategorized is "
        f"expected, not a gap: those get a human/agent read, never a forced guess."
    )


if __name__ == "__main__":
    main()
